/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { GTP } from "./GTP";
export * as factories from "./factories";
export { GTP__factory } from "./factories/GTP__factory";
